// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// triangulate_matrix_rcpp
List triangulate_matrix_rcpp(NumericMatrix heightmap, float maxError, int maxTriangles);
RcppExport SEXP _terrainmeshr_triangulate_matrix_rcpp(SEXP heightmapSEXP, SEXP maxErrorSEXP, SEXP maxTrianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type heightmap(heightmapSEXP);
    Rcpp::traits::input_parameter< float >::type maxError(maxErrorSEXP);
    Rcpp::traits::input_parameter< int >::type maxTriangles(maxTrianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(triangulate_matrix_rcpp(heightmap, maxError, maxTriangles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terrainmeshr_triangulate_matrix_rcpp", (DL_FUNC) &_terrainmeshr_triangulate_matrix_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_terrainmeshr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
